### ISSUE TITLE
Installing with -Dwith-python=3 and -Dwith-mpi=ON leads to test failures

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1292]
# Problem
When following the steps in the [installation guide](https://nest-simulator.readthedocs.io/en/latest/installation/linux_install.html) with 2 extra configuration options `-Dwith-python=3` and `-Dwith-mpi=ON` a test during Phase 7 of `make installcheck` fails. 

# Minimal reproduction steps:
1) Install Ubuntu 18.04.3
2) Download nest2.18 tarball, unpack
3) Install dependencies from list in installation guide, replacing `python-*` packages with `python3-*`
4) `cmake -Dwith-python=3 -Dwith-mpi=ON -DCMAKE_INSTALL_PREFIX:PATH=/nest/2.18 /unpack/path/`
5) `make`
6) `make install`
7) `make installcheck` leads to an error

# Error
```
  Running test testWithMPI...
Traceback (most recent call last):
  File "/nest/2.18/lib/python3.6/site-packages/nest/tests/test_sp/mpitest_issue_578_sp.py", line 26, in <module>
    import nest
  File "/nest/2.18/lib/python3.6/site-packages/nest/__init__.py", line 26, in <module>
    from . import ll_api      # noqa
  File "/nest/2.18/lib/python3.6/site-packages/nest/ll_api.py", line 72, in <module>
Traceback (most recent call last):
  File "/nest/2.18/lib/python3.6/site-packages/nest/tests/test_sp/mpitest_issue_578_sp.py", line 26, in <module>
    import nest
  File "/nest/2.18/lib/python3.6/site-packages/nest/__init__.py", line 26, in <module>
    from . import ll_api      # noqa
  File "/nest/2.18/lib/python3.6/site-packages/nest/ll_api.py", line 72, in <module>
    from . import pynestkernel as kernel      # noqa
ImportError: dynamic module does not define init function (initpynestkernel)
    from . import pynestkernel as kernel      # noqa
ImportError: dynamic module does not define init function (initpynestkernel)
```

# Reports
The archive of the reports instructed to attach to the issue: 
[reports.zip](https://github.com/nest/nest-simulator/files/3610443/reports.zip)

**Comment by stinebuu** [comment]
@Helveg sorry for not following up on this. Does the problem still persist? Have you tried with 2.20?

**Comment by Helveg** [comment]
Well we haven't noticed any actual problems with NEST and MPI so didn't look into this any further either.

**Comment by heplesser** [comment]
Ok, then I will close the issue. Please re-open if the problem should pop up again.
