### ISSUE TITLE
Can't import NEST in Pycharm

### ISSUE THREAD

**Issue by daphnecor** [nest/nest-simulator#1412]
I used NEST before by making a new virtual environment and jupyter notebooks but I'm trying to use Pycharm now, I keep getting this error.

```
>> import nest

Traceback (most recent call last):
  File "/Users/Daphne/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-d0a3dc3bba7c>", line 1, in <module>
    import nest
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/Daphne/anaconda3/lib/python3.7/site-packages/nest.py", line 4
    if isinstance(each_item, indent = False ,list):
                                            ^
SyntaxError: positional argument follows keyword argument
```

**Comment by clinssen** [comment]
I'm not aware of a nest.py belonging to NEST Simulator, although I don't have any experience with anaconda. Could it be an unrelated file also called "nest", but belonging to something else? Could you post the file somewhere?

**Comment by steffengraber** [comment]
#1232 This may be related.

**Comment by daphnecor** [comment]
I'm still not sure about the exact cause of the problem, changed to a setup with spyder and jupyter notebooks.

**Comment by daphnecor** [comment]
It may be related to the integration of conda environments and Pycharm, which is not always easy
