### ISSUE TITLE
Using GetConnections as documented results in TypeError

### ISSUE THREAD

**Issue by w-klijn** [nest/nest-simulator#154]
When using the function GetConnections calling with an empty dictionary should result in all connections being returned. It aborts with an Type error:

Minimal code example:
import nest
nest.GetConnections({})  # Error also occurs in a populated model

Traceback (most recent call last):
  File "getconnections.py", line 3, in <module>
    nest.GetConnections({})
  File "/home/ubuntu/build/nest2.8.0/opt/nest/lib/python2.7/site-packages/nest/hl_api.py", line 154, in stack_checker_func
    return f(*args, **kwargs)
  File "/home/ubuntu/build/nest2.8.0/opt/nest/lib/python2.7/site-packages/nest/hl_api.py", line 813, in GetConnections
    raise TypeError("source must be a list of GIDs")
TypeError: source must be a list of GIDs

**Comment by w-klijn** [comment]
The documentation I followed was apparently for a different function:
I should use the interface of: nest.hl_api.GetConnections.
