### ISSUE TITLE
Your Cython version is too old.  Please install newer version (0.19.2+)

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#1746]
On Linux I get the following error while trying to reproduce Carlos's error:

```
CMake Error at cmake/ProcessOptions.cmake:416 (message):
  Your Cython version is too old.  Please install newer version (0.19.2+)
Call Stack (most recent call first):
  CMakeLists.txt:155 (nest_process_with_python)
```

... although I have Cython `0.29.21` loaded via Spack.

**Comment by jougs** [comment]
What does `which cython` and `cython --version` give you? Can the Spack-installed version be found properly?

**Comment by ikitayama** [comment]
@jougs looks like it is not installed properly.

```
-bash-4.2$ spack load py-cython
==> Error: py-cython matches multiple packages.
  Matching packages:
    wjrpqfy py-cython@0.29.16%gcc@10.1.0 arch=linux-centos7-nehalem
    mxfnrdp py-cython@0.29.21%gcc@10.2.0 arch=linux-centos7-nehalem
  Use a more specific spec.
-bash-4.2$ spack load py-cython /mxf
-bash-4.2$ cython --version
Traceback (most recent call last):
  File "/home/itaru/projects/spack/opt/spack/linux-centos7-nehalem/gcc-10.2.0/py-cython-0.29.21-mxfnrdpotqks376dot56vkcbxlfhmkjq/bin/cython", line 7, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
-bash-4.2$ spack load py-cython /wjr
-bash-4.2$ cython --version
Traceback (most recent call last):
  File "/home/itaru/projects/spack/opt/spack/linux-centos7-nehalem/gcc-10.1.0/py-cython-0.29.16-wjrpqfy3azmjwymqmqoevows3qijorli/bin/cython", line 7, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by ikitayama** [comment]
Spack seems to install `cython, cython-2, and cython-2.7,` does NEST assume just cython?

**Comment by ikitayama** [comment]
Cython Spack package is being fixed in https://github.com/spack/spack/pull/18572

**Comment by ikitayama** [comment]
The issue is fixed in the Spack develop branch and now I am able to configure NEST with Python (Cython).
