### ISSUE TITLE
NEST install process does not declare its Python dependencies to Python

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1931]
**Describe the bug**
NEST's python module relies on `numpy` but does not declare this dependency to the Python interpreter targetted in the install process. This leads to missing dependencies even though the installation instructions are followed, if a user uses a clean virtual environment:

```
robin@TNG2019:~$ python
Python 3.9.1 (default, Feb 18 2021, 16:03:49)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nest
[INFO] [2021.2.18 16:12:16 /home/robin/nest-simulator/nestkernel/rng_manager.cpp:217 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2021.2.18 16:12:16 /home/robin/nest-simulator/nestkernel/rng_manager.cpp:260 @ Network::create_grng_] : Creating new default global RNG

              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: master@ed1249da
 Built: Feb 18 2021 16:09:45

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.


Feb 18 16:12:16 evalrcfile [Warning]:
    NEST has created its configuration file $HOME/.nestrc

Feb 18 16:12:16 evalrcfile [Warning]:
    If this troubles you, type '/nestrc help' at the prompt to learn more.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/nest-install/lib/python3.9/site-packages/nest/__init__.py", line 30, in <module>
    from .hl_api import *      # noqa
  File "/home/robin/nest-install/lib/python3.9/site-packages/nest/hl_api.py", line 40, in <module>
    _il.import_libs(__file__, globals(), 'lib', ignore=_ignore_modules)
  File "/home/robin/nest-install/lib/python3.9/site-packages/nest/import_libs.py", line 82, in import_libs
    exec(code, mod_dict, mod_dict)
  File "/home/robin/nest-install/lib/python3.9/site-packages/nest/hl_api.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "/home/robin/nest-install/lib/python3.9/site-packages/nest/lib/hl_api_connections.py", line 26, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

**To Reproduce**
1. Set up a clean `pyenv`, `venv` or `virtualenv` virtual environment
2. Build NEST
3. Source `install/bin/nest_vars.sh`
4. Import nest

**Expected behavior**
NEST's python module should be a proper Python package that declares its dependencies to the correct Python interpreter rather than instructing to install `numpy` to the system Python. See also https://github.com/nest/nest-simulator/issues/1870

**Comment by Helveg** [comment]
@gtrensch in the end we didn't settle on a solution for this one: Are we using `ensurepip` and `pip` to install the Python dependencies for the user (maybe only in the new default proposed in #1948), or do we leave it up to the user to do this seperately and update the install instructions as outlined in https://github.com/nest/nest-simulator/issues/1870 so that the install instructions for Python deps also target the active Python env?
