### ISSUE TITLE
Conngen module problem

### ISSUE THREAD

**Issue by mdjurfeldt** [nest/nest-simulator#206]
Running csademo.py in the following archive:
[csademo.zip](https://github.com/nest/nest-simulator/files/90348/csademo.zip)
invokes CGConnect, which generates the following error:

Traceback (most recent call last):
  File "csademo.py", line 9, in <module>
    nest.CGConnect (p0, p1, cg)
  File "/usr/local/lib/python2.7/dist-packages/nest/lib/hl_api_helper.py", line 138, in stack_checker_func
    return f(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nest/lib/hl_api_connections.py", line 617, in CGConnect
    if _is_subnet_instance(pre[:1]):
  File "/usr/local/lib/python2.7/dist-packages/nest/lib/hl_api_connections.py", line 594, in _is_subnet_instance
    GetChildren(gids)
NameError: global name 'GetChildren' is not defined

**Comment by heplesser** [comment]
@mdjurfeldt Sorry for the very late response. We removed `GetChildren`, `GetLeaves` etc some time ago and replaced them by `GetGlobalChildren`/`GetLocalChildren`, `GetGlobalLeaves`/`GetLocalLeaves` etc. The reason for this was to make explicit what you are asking for. The `Global` variants collect information from all MPI processes, which may be very slow and require a lot of memory. The `Local` variants only collect information from the MPI process running the command.

**Comment by jougs** [comment]
This i related to and fixed by #483.

**Comment by jougs** [comment]
Fixed by the merge of #483.
