### ISSUE TITLE
`ImportError: libnest.so: cannot open shared object file` w. NEST v3.0

### ISSUE THREAD

**Issue by espenhgn** [nest/nest-simulator#2075]
**Describe the bug**
Since d83005bc0 / 8d1df45d7 pyNEST doesn't quite know where to look for installed NEST dynamic libraries on certain platforms (at least on JUSUF/JURECA using my usual install procedure found below):
```
$ ldd /p/home/jusers/hagen2/jusuf/.local/nest/lib/python3.8/site-packages/nest/pynestkernel.so 
	linux-vdso.so.1 =>  (0x00007ffebfa57000)
	libpython3.8.so.1.0 => /p/software/jusuf/stages/2020/software/Python/3.8.5-GCCcore-9.3.0/lib/libpython3.8.so.1.0 (0x00002ae7e57c3000)
	libnest.so => not found
	libmodels.so => not found
	libnestkernel.so => not found
	libltdl.so.7 => /p/software/jusuf/stages/2020/software/libtool/2.4.6-GCCcore-9.3.0/lib/libltdl.so.7 (0x00002ae7e565a000)
	libsli.so => not found
	libnestutil.so => not found
	libgsl.so.25 => /p/software/jusuf/stages/2020/software/GSL/2.6-GCC-9.3.0/lib/libgsl.so.25 (0x00002ae7e5ba9000)
	libgslcblas.so.0 => /p/software/jusuf/stages/2020/software/GSL/2.6-GCC-9.3.0/lib/libgslcblas.so.0 (0x00002ae7e5666000)
	libgomp.so.1 => /p/software/jusuf/stages/2020/software/GCCcore/9.3.0/lib64/libgomp.so.1 (0x00002ae7e5767000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00002ae7e6129000)
	libstdc++.so.6 => /p/software/jusuf/stages/2020/software/GCCcore/9.3.0/lib64/libstdc++.so.6 (0x00002ae7e6345000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00002ae7e6536000)
	libgcc_s.so.1 => /p/software/jusuf/stages/2020/software/GCCcore/9.3.0/lib64/libgcc_s.so.1 (0x00002ae7e57a0000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00002ae7e6838000)
	libcrypt.so.1 => /usr/lib64/libcrypt.so.1 (0x00002ae7e6c06000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00002ae7e6e3d000)
	libutil.so.1 => /usr/lib64/libutil.so.1 (0x00002ae7e7041000)
	/lib64/ld-linux-x86-64.so.2 (0x00002ae7e559f000)
	libfreebl3.so => /usr/lib64/libfreebl3.so (0x00002ae7e7244000)
```
I have to manually update `LD_LIBRARY_PATH` to fix this issue as `export LD_LIBRARY_PATH=/p/home/jusers/hagen2/jusuf/.local/nest/lib64/nest:$LD_LIBRARY_PATH` as the installed `nest_vars.sh` script only updates `PATH` and `PYTHONPATH`.  

**To Reproduce**
```
$ module use  $OTHERSTAGES
$ module load Stages/2020
$ module load GCC/9.3.0 ParaStationMPI/5.4.7-1 \
Autotools/20200321 CMake/3.18.0 Doxygen/1.8.18 \
GSL/2.6 git/2.28.0 \
SciPy-Stack/2020-Python-3.8.5 \
h5py/2.10.0-serial-Python-3.8.5 \
scikit/2020-Python-3.8.5 \
mpi4py/3.0.3-Python-3.8.5 Boost.Python
$ pip install junitparser --user
$ export NESTSOURCES=$HOME/sources/nest-simulator
$ export NESTBLD=$HOME/sources/nest-simulator.bld_JUSUF
$ export NESTPREFIX=$HOME/.local/nest
$ cd sources
$ git clone https://github.com/nest/nest-simulator.git
$ cd $NESTSOURCES
$ git checkout v3.0
$ mkdir $NESTBLD
$ cd $NESTBLD
$ rm -r $NESTPREFIX
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$NESTPREFIX $NESTSOURCES
$ make -j
$ make install
$ cd
$ source /p/home/jusers/hagen2/jusuf/.local/nest/bin/nest_vars.sh
$ python -c "import nest"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/p/home/jusers/hagen2/jusuf/.local/nest/lib/python3.8/site-packages/nest/__init__.py", line 47, in <module>
    from . import ll_api                  # noqa
  File "/p/home/jusers/hagen2/jusuf/.local/nest/lib/python3.8/site-packages/nest/ll_api.py", line 51, in <module>
    from . import pynestkernel as kernel      # noqa
ImportError: libnest.so: cannot open shared object file: No such file or directory
```

**Expected behavior**
Dynamic libraries being found automatically (or `nest_vars.sh` should update `LD_LIBRARY_PATH` as well). 

**Screenshots**

**Desktop/Environment (please complete the following information):**
 - OS: CentOS 7
 - Browser: [if applicable, e.g. chrome, safari]
 - Shell: bash
 - Python-Version: 3.8
 - NEST-Version: v3.0
 - Installation:
```
--------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Build type          : 
Target System       : Linux
Cross Compiling     : FALSE
C compiler          : GNU 9.3.0 (/p/software/jusuf/stages/2020/software/GCCcore/9.3.0/bin/cc)
C compiler flags    :  -O2 -Wall -fopenmp -fdiagnostics-color=auto
C++ compiler        : GNU 9.3.0 (/p/software/jusuf/stages/2020/software/GCCcore/9.3.0/bin/c++)
C++ compiler flags  :  -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto
Build dynamic       : ON

Built-in modules    : models
User modules        : None
Python bindings     : Yes (Python 3.8.5: /p/software/jusuf/stages/2020/software/Python/3.8.5-GCCcore-9.3.0/bin/python3.8)
       Includes     : /p/software/jusuf/stages/2020/software/Python/3.8.5-GCCcore-9.3.0/include/python3.8
       Libraries    : /p/software/jusuf/stages/2020/software/Python/3.8.5-GCCcore-9.3.0/lib/libpython3.8.so

Cython bindings     : Yes (Cython 0.29.21: /p/software/jusuf/stages/2020/software/Python/3.8.5-GCCcore-9.3.0/bin/cython)
MPI4PY header	    : NO 
Use threading       : Yes (OpenMP: -fopenmp)
Use GSL             : Yes (GSL 2.6)
    Includes        : /p/software/jusuf/stages/2020/software/GSL/2.6-GCC-9.3.0/include
    Libraries       : /p/software/jusuf/stages/2020/software/GSL/2.6-GCC-9.3.0/lib/libgsl.so;/p/software/jusuf/stages/2020/software/GSL/2.6-GCC-9.3.0/lib/libgslcblas.so

Use Readline        : Yes (GNU Readline 8.0)
    Includes        : /p/software/jusuf/stages/2020/software/libreadline/8.0-GCCcore-9.3.0/include
    Libraries       : /p/software/jusuf/stages/2020/software/libreadline/8.0-GCCcore-9.3.0/lib/libreadline.so;/p/software/jusuf/stages/2020/software/ncurses/6.2-GCCcore-9.3.0/lib/libncurses.so

Use libltdl         : Yes (LTDL 2.4.6)
    Includes        : /p/software/jusuf/stages/2020/software/libtool/2.4.6-GCCcore-9.3.0/include
    Libraries       : /p/software/jusuf/stages/2020/software/libtool/2.4.6-GCCcore-9.3.0/lib/libltdl.so

Use doxygen         : Yes (/p/software/jusuf/stages/2020/software/Doxygen/1.8.18-GCCcore-9.3.0/bin/doxygen)
                    : target `doc` available
Use MPI             : No
Detailed timers     : No

Use MUSIC           : No
Use libneurosim     : No
Use Boost           : Yes (Boost 1.74.0)
    Includes        : /p/software/jusuf/stages/2020/software/Boost.Python/1.74.0-gpsmpi-2020/include
    Libraries       : 

Use recording backend Arbor   : No
Use SIONlib         : No

--------------------------------------------------------------------------------

The NEST executable will be installed to:
  /p/home/jusers/hagen2/jusuf/.local/nest/bin/

NEST dynamic libraries and user modules will be installed to:
  /p/home/jusers/hagen2/jusuf/.local/nest/lib64/nest/

Documentation and examples will be installed to:
  /p/home/jusers/hagen2/jusuf/.local/nest/share/doc/nest/

PyNEST will be installed to:
    /p/home/jusers/hagen2/jusuf/.local/nest/lib/python3.8/site-packages

To set necessary environment variables, add the following line
to your ~/.bashrc :
  source /p/home/jusers/hagen2/jusuf/.local/nest/bin/nest_vars.sh

--------------------------------------------------------------------------------
```
**Additional context**
I encounter the same issue on JURECA. 253641b95 is the last commit that works on my end.

**Comment by Helveg** [comment]
The commit you linked in the additional context is on a side branch, could you check that the bug is introduced between commits on the master branch 4de6c4a9317f7e9abbb904413bbcec5c88af09a9 and 396b6a8835475fae471ae58f26752d9049d441b9?

**Comment by Helveg** [comment]
@espenhgn Could you try building with the [python-libdir branch of Helveg/nest-simulator](https://github.com/Helveg/nest-simulator/tree/python-libdir)?

**Comment by espenhgn** [comment]
@Helveg, thanks for looking into this. 

Your branch works, but:
```
PyNEST will be installed to:
    /p/home/jusers/hagen2/jusuf/.local/nest/lib64/python./site-packages
```
so the Python major/minor version is somehow missed in the target path. Is that intentional? I would've though `<DCMAKE_INSTALL_PATH:PATH>/lib/pythonX.Y/site-packages` should be preferred destination (say for conda/virtualenv envs where calling `nest_vars.sh` ought to be redundant. I have in the path usually set the install destination to `$CONDA_PREFIX` without issues and it appears that this will now be an issue. 

And yes, #2079 is indeed a duplicate of this issue.

**Comment by Helveg** [comment]
Not intentional ;p Just missing some vars in that scope :)

**Comment by Helveg** [comment]
@espenhgn Does my latest commit work? `${Python_VERSION}` is exported to the parent scope, but I'm not sure that it is exactly equivalent to `${Python_VERSION_MAJOR}.${Python_VERSION_MINOR}`

**Comment by espenhgn** [comment]
Looks good to me! Also tried your suggestion w. conda - works fine.
