### ISSUE TITLE
Building NEST wheels on `manylinux` image leads to an error because boost is missing

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#2409]
**Describe the bug**
This bug is specific for a WIP branch of @hakonsbm and @jougs. When trying to build the NEST wheels on the manylinux image I run into the following error:

```
[root@a669f15604b9 project]# NEST_INSTALL_NODOC=TRUE python3.9 setup.py bdist_wheel -- -DCMAKE_MODULE_PATH=/project/cmak
e:/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/skbuild/resources/cmake -- -j4


--------------------------------------------------------------------------------
-- Trying "Ninja" generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-10/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-10/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /project/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Ninja" generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /project/_skbuild/linux-x86_64-3.9/cmake-build
  Command:
    cmake /project -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/project/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.7 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/usr/local/bin/python3.9 -DPython3_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.9.7/include/python3.9 -DPython3_LIBRARY:PATH=libpython3.9.a -DPython3_NumPy_INCLUDE_DIRS:PATH=/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/numpy/core/include -DPython_EXECUTABLE:FILEPATH=/usr/local/bin/python3.9 -DPython_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.9.7/include/python3.9 -DPython_LIBRARY:PATH=libpython3.9.a -DPython_NumPy_INCLUDE_DIRS:PATH=/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/numpy/core/include -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.9 -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.9.7/include/python3.9 -DPYTHON_LIBRARY:PATH=libpython3.9.a -DPYTHON_NumPy_INCLUDE_DIRS:PATH=/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/ninja/data/bin/ninja -DCMAKE_MODULE_PATH=/project/cmake:/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Host triple: x86_64-pc-linux
-- Target triple: x86_64-pc-linux
-- Found Cython: /opt/_internal/cpython-3.9.7/bin/cython (found suitable version "0.29.24", minimum required is "0.28.3")
-- Could NOT find Readline (missing: READLINE_LIBRARY NCURSES_LIBRARY READLINE_INCLUDE_DIR)
-- Could NOT find GSL (missing: GSL_INCLUDE_DIR GSL_LIBRARY GSL_CBLAS_LIBRARY) (found version "")
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR) (Required is at least version "1.69.0")
-- Check the abort exitcode.
-- Check the abort exitcode. 134
-- Check the segmentation fault exitcode.
-- Check the segmentation fault exitcode. 139
-- Check whether the compiler ignores cmath makros.
-- Check whether the compiler ignores cmath makros. OFF
-- Check whether the compiler does NOT include <*.h> headers ISO conformant.
-- Check whether the compiler does NOT include <*.h> headers ISO conformant. OFF
-- Check whether the compiler respects symbolic signal names in signal.h.
-- Check whether the compiler respects symbolic signal names in signal.h. OFF
-- Check static template member declaration.
-- Check static template member declaration. OFF
-- Check for STL vector capacity base unity.
-- Check for STL vector capacity base unity. ON
-- Check for STL vector capacity doubling strategy.
-- Check for STL vector capacity doubling strategy. ON
-- Check whether the compiler fails with ICE.
-- Check whether the compiler fails with ICE. OFF
-- Check if ::nan is available from cmath.
-- Check if ::nan is available from cmath. ON
-- Check if ::isnan is available from cmath.
-- Check if ::isnan is available from cmath. ON
-- Check if Random123 generators work.
-- Check if Random123 generators work. ON
-- NEST version: reinvention-of-the-wheel@6880e7c669

--------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Build type          : Release
Target System       : Linux
Cross Compiling     : FALSE
C compiler          : GNU 10.2.1 (/opt/rh/devtoolset-10/root/usr/bin/cc)
C compiler flags    :  -O2 -Wall -fopenmp -fdiagnostics-color=auto   -O3 -DNDEBUG
C++ compiler        : GNU 10.2.1 (/opt/rh/devtoolset-10/root/usr/bin/c++)
C++ compiler flags  :  -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto -O3 -DNDEBUG
Build dynamic       : ON

Built-in modules    : models
User modules        : None
Python bindings     : Yes (Python 3.9.7: /usr/local/bin/python3.9)
       Includes     : /opt/_internal/cpython-3.9.7/include/python3.9
       Libraries    :

Cython bindings     : Yes (Cython 0.29.24: /opt/_internal/cpython-3.9.7/bin/cython)
MPI4PY header       : NO
Use threading       : Yes (OpenMP: -fopenmp)
Use GSL             : No
Use Readline        : No
Use libltdl         : Yes (LTDL 2.4.6)
    Includes        : /usr/local/include
    Libraries       : /usr/local/lib/libltdl.so

Use doxygen         : No
Use MPI             : No
Detailed timers     : No

Use MUSIC           : No
Use libneurosim     : No
Use Boost           : No
Use SIONlib         : No

--------------------------------------------------------------------------------

The NEST executable will be installed to:
  /project/_skbuild/linux-x86_64-3.9/cmake-install/bin/

NEST dynamic libraries and user modules will be installed to:
  /project/_skbuild/linux-x86_64-3.9/cmake-install/lib64/nest/

Documentation and examples will be installed to:
  /project/_skbuild/linux-x86_64-3.9/cmake-install/share/doc/nest/

PyNEST will be installed to:
    /project/_skbuild/linux-x86_64-3.9/cmake-install/lib64/python3.9/site-packages

To set necessary environment variables, add the following line
to your ~/.bashrc :
  source /project/_skbuild/linux-x86_64-3.9/cmake-install/bin/nest_vars.sh

--------------------------------------------------------------------------------


ATTENTION!
You are about to compile NEST without the GNU Scientific
Library or your GSL is too old (before v1.11). This means
that conductance-based neuron models and some random number
generators will not be available.

--------------------------------------------------------------------------------

You can now build and install NEST with
  make
  make install
  make installcheck

If you experience problems with the installation or the use of NEST,
please see https://www.nest-simulator.org/frequently_asked_questions
or go to https://www.nest-simulator.org/community to find out how to
join the user mailing list.

-- Configuring done
-- Generating done
-- Build files have been written to: /project/_skbuild/linux-x86_64-3.9/cmake-build
[1/234] Building CXX object libnestutil/CMakeFiles/nestutil.dir/dictionary.cpp.o
FAILED: libnestutil/CMakeFiles/nestutil.dir/dictionary.cpp.o
/opt/rh/devtoolset-10/root/usr/bin/c++ -Dnestutil_EXPORTS -I/project/libnestutil -I/project/_skbuild/linux-x86_64-3.9/cmake-build/libnestutil -I/project/nestkernel -I/project/sli -I/project/thirdparty -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto -O3 -DNDEBUG -fPIC -MD -MT libnestutil/CMakeFiles/nestutil.dir/dictionary.cpp.o -MF libnestutil/CMakeFiles/nestutil.dir/dictionary.cpp.o.d -o libnestutil/CMakeFiles/nestutil.dir/dictionary.cpp.o -c /project/libnestutil/dictionary.cpp
/project/libnestutil/dictionary.cpp:24:10: fatal error: boost/any.hpp: No such file or directory
   24 | #include <boost/any.hpp>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
[2/234] Building CXX object libnestutil/CMakeFiles/nestutil.dir/dictionary_access_flag_manager.cpp.o
FAILED: libnestutil/CMakeFiles/nestutil.dir/dictionary_access_flag_manager.cpp.o
/opt/rh/devtoolset-10/root/usr/bin/c++ -Dnestutil_EXPORTS -I/project/libnestutil -I/project/_skbuild/linux-x86_64-3.9/cmake-build/libnestutil -I/project/nestkernel -I/project/sli -I/project/thirdparty -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto -O3 -DNDEBUG -fPIC -MD -MT libnestutil/CMakeFiles/nestutil.dir/dictionary_access_flag_manager.cpp.o -MF libnestutil/CMakeFiles/nestutil.dir/dictionary_access_flag_manager.cpp.o.d -o libnestutil/CMakeFiles/nestutil.dir/dictionary_access_flag_manager.cpp.o -c /project/libnestutil/dictionary_access_flag_manager.cpp
In file included from /project/libnestutil/dictionary_access_flag_manager.h:30,
                 from /project/libnestutil/dictionary_access_flag_manager.cpp:29:
/project/libnestutil/dictionary.h:26:10: fatal error: boost/any.hpp: No such file or directory
   26 | #include <boost/any.hpp>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
[4/234] Building CXX object libnestutil/CMakeFiles/nestutil.dir/logging_event.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/skbuild/cmaker.py", line 680, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/opt/_internal/cpython-3.9.7/lib/python3.9/site-packages/skbuild/cmaker.py", line 704, in make_impl
    raise SKBuildError(

An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release -- -j4
  Install target:
    install
  Source directory:
    /project
  Working directory:
    /project/_skbuild/linux-x86_64-3.9/cmake-build
Please check the install target is valid and see CMake's output for more information
```

What we see:

1. CMake knows Boost is missing
2. `dictionary.cpp` includes boost anyway. Is this new code specific to your undertaking @hakonsbm ?

Should I work around this by installing Boost for now? If so, how?

**Comment by hakonsbm** [comment]
Thanks for reporting this. I assume you are referring to the [new-pynest branch](https://github.com/hakonsbm/nest-simulator/tree/new-pynest) in my fork. Boost is currently required by the dictionary implementation in dictionary.cpp. Eventually we may move to a mixed C++17/Boost implementation or a pure C++17 implementation, but as a workaround right now you should install with Boost (you only need the Boost headers) and NEST will look for them by default. I'm not sure how install Boost with wheels in manylinux, perhaps there is some package for it?

As a side note, to keep things tidy, issues here should only concern nest-simulator/master or any of the other branches in nest-simulator. I just turned on [issues for my fork](https://github.com/hakonsbm/nest-simulator/issues), so issues regarding the new-pynest branch (or any other of my branches) can be created there instead. I'm therefore closing this issue, further issues should be discussed there.
