### ISSUE TITLE
Read the Docs build fails on master

### ISSUE THREAD

**Issue by jessica-mitchell** [nest/nest-simulator#2576]
**Describe the bug**

Read the docs fails to build with the following error:
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/nest-simulator/envs/2495/lib/python3.8/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nest-simulator/checkouts/2495/doc/htmldoc/conf.py", line 71, in <module>
    mockedmodule += convert(fin)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nest-simulator/checkouts/2495/doc/htmldoc/mock_kernel.py", line 79, in convert
    tree = ast.parse(res_tmp)
  File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 180
    array_long_mv = numpy.ascontiguousarray(array, dtype=)
```

**To Reproduce**
1. Build Read the Docs from the master branch

This is related to a change in the pynestkernel.pyx file in PR #2571:

```
-                array_long_mv = numpy.ascontiguousarray(array, dtype=numpy.int_)
+                array_long_mv = numpy.ascontiguousarray(array, dtype=int)
```
Read the docs build passes using the older syntax.

@heplesser We can revert it back to the original, but not sure if there is a better alternative that doesnt use the numpy syntax?

**Comment by steffengraber** [comment]
If I'm using 

`array_long_mv = numpy.ascontiguousarray(array, dtype=int32)`

instead of

`array_long_mv = numpy.ascontiguousarray(array, dtype=int)`

in pynestkernel.pyx sphinx passes through.

Only tested locally so far.
