### ISSUE TITLE
Unsorted node collection indices lead to unclear error message

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#2639]
**Describe the bug**

```
>>> import nest, numpy as np
>>> a = nest.Create("iaf_cond_alpha", 20000)
>>> a[np.array([3, 34,444])]
NodeCollection(metadata=None,
               model=iaf_cond_alpha, size=1, first=10;
               model=iaf_cond_alpha, size=1, first=41;
               model=iaf_cond_alpha, size=1, first=451)
>>> a[[34,444,3]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/.pyenv/versions/bsb/lib/python3.9/site-packages/nest/lib/hl_api_types.py", line 268, in __getitem__
    return take_array_index(self._datum, key)
  File "pynestkernel.pyx", line 286, in pynestkernel.NESTEngine.take_array_index
nest.lib.hl_api_exceptions.BadProperty: BadProperty in SLI function take_array_index
```

**Expected behavior**
I expect an error message that tells me that I should use sorted indices, or for NEST to sort them for me.

**Desktop/Environment (please complete the following information):**
 - OS: WSL 2, Ubuntu 18, Windows 10
 - Python-Version: 3.9
 - NEST-Version: master@4872b8cbb9
 - Installation: CMake

**Comment by heplesser** [comment]
@med-ayssar Thanks for the hint, but since we are moving to pynest-ng with slightly different error handling, I would first want to see how pynest-ng behaves in this case and then look for how to improve things.

**Comment by jessica-mitchell** [comment]
@alpinangu Hi can you check if this issue is still relevant since pynest-ng merge? thanks!

**Comment by alpinangu** [comment]
> [@alpinangu](https://github.com/alpinangu) Hi can you check if this issue is still relevant since pynest-ng merge? thanks!

Hi, the issue persists, but there is now an explanatory error message:

`NESTErrors.BadProperty: Indices must be sorted in ascending order`

**Comment by Helveg** [comment]
As far as I'm concerned the explanatory error message fully addresses the issue :)
