### ISSUE TITLE
ImportError: cannot import name 'pynestkernel'

### ISSUE THREAD

**Issue by andraderenew** [nest/nest-simulator#862]
When I import nest in python 3.6 I can´t. This appears in the screen 
>>> import nest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andraderenew/Downloads/nest-2.14.0/pynest/nest/__init__.py", line 70, in <module>
    from . import pynestkernel as _kernel      # noqa
ImportError: cannot import name 'pynestkernel'
>>> 

Also if I try to open a file with python it gives me the same error

Renes-MacBook-Air:~ andraderenew$ python /Users/andraderenew/Downloads/nest-2.14.0/pynest/examples/balancedneuron.py 
Traceback (most recent call last):
  File "/Users/andraderenew/Downloads/nest-2.14.0/pynest/examples/balancedneuron.py", line 46, in <module>
    import nest
  File "/Users/andraderenew/Downloads/nest-2.14.0/pynest/nest/__init__.py", line 70, in <module>
    from . import pynestkernel as _kernel      # noqa
ImportError: cannot import name 'pynestkernel'

**Comment by heplesser** [comment]
@andraderenew Probably something went wrong when you installed NEST. I am surprised that you are loading `nest-2.14.0/pynest/nest/__init__.py` from the source code directory, not from an installation directory. Is your `PYTHONPATH` set correctly?

Generally, this type of problem is better discussed on the NEST User mailing list. You should also provide more information about how you installed NEST and what system you are using. I am closing the issue and would ask you to post on NEST User if the problem persists.
